#!/usr/bin/env ruby

require 'bundler/setup'
require 'scale_rb'
require 'json'
require 'optparse'

# ./exe/metadata https://polkadot-rpc.dwellir.com -b 0xfc2d86c5a2cc92b7770dcc14e74116912c9f848000b5f4ceca6fe1475588692c
# ./exe/metadata https://polkadot-rpc.dwellir.com -b 22931689
# ./exe/metadata https://polkadot-rpc.dwellir.com
@options = {}
parser = OptionParser.new do |opts|
  opts.banner = 'Usage: metadata [url] [options]'
  opts.on('-bNUMBERORHASH', '--block=NUMBERORHASH', 'Block number or hash') do |value|
    @options[:block] = value
  end
end

if ARGV.empty?
  puts parser
else
  parser.parse!
  url = ARGV[0]

  client = ScaleRb::HttpClient.new(url)

  block_hash = nil
  if @options[:block]
    if @options[:block].length == 66
      block_hash = @options[:block]
    else
      block_number = @options[:block].to_i
      block_hash = client.chain_getBlockHash(block_number)
    end
  end

  metadata = client.get_metadata(block_hash)
  puts metadata.to_json
end
