#!/usr/bin/env ruby

require 'bundler/setup'
require 'scale_rb'
require 'json'
require 'optparse'

def print_metadata(url, at = nil)
  puts JSON.pretty_generate(HttpClient.get_metadata(url, at))
end

# ./bin/metadata http://g2.dev.darwinia.network:2234 -b 0x23ebddd6519aaf1b7fc916c3709af13d7a4010943fb53038406581171000a58e
# ./bin/metadata https://rpc.darwinia.network -b 10511703
# ./bin/metadata https://pangoro-rpc.darwinia.network
@options = {}
parser = OptionParser.new do |opts|
  opts.banner = 'Usage: metadata [url] [options]'
  opts.on('-bNUMBERORHASH', '--block=NUMBERORHASH', 'Block number or hash') do |value|
    @options[:block] = value
  end
end

if ARGV.empty?
  puts parser
else
  parser.parse!
  url = ARGV[0]

  if @options[:block]
    if @options[:block].length == 66
      block_hash = @options[:block]
    else
      block_number = @options[:block].to_i
      block_hash = HttpClient.chain_getBlockHash url, block_number
    end
  else
    block_hash = HttpClient.chain_getBlockHash url
  end

  print_metadata url, block_hash
end
